### ISSUE TITLE
Build is not working on an LXC Container

### ISSUE THREAD

**Issue by boospy** [baderas/package-jetbrains-ide#4]
Hello, 

we have all us buildmachines under lxc. But we get some error to build pycharm. On KVM and normal Desktops this is working fine. Here is the error on Debian9 and Ubuntu 16.04 LXC on Proxmox5. 
```
root@build-debian:~/package-jetbrains-ide# python3  package.py -i pycharm -e community
Downloading [##########] 100%Traceback (most recent call last):
  File "package.py", line 285, in <module>
    for line in file1:
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 841: ordinal not in range(128)

```

**Comment by pix106** [comment]
The exact same happens to me using a debian 9 docker container when interactively running package.py from the container console.
When run from Dockerfile without interacting, it works just fine.

Edit : no problem when using python:rc-alpine as base

**Comment by boospy** [comment]
Any fixes would be really great :)

**Comment by pix106** [comment]
IINM the fix is to setup locale in your Dockerfile
